load('parmASHmean.Rdata')
usethis::use_data(parmASHmean,overwrite=T)
load('~/SimingLab/jiezhou/diffdriver/data-raw/ff.Rd')
usethis::use_data(ff,overwrite = T)
load('~/SimingLab/jiezhou/diffdriver/data-raw/ll.Rd')
usethis::use_data(ll,overwrite = T)
load('~/SimingLab/jiezhou/diffdriver/data-raw/codeSignature.Rd')
codeSignature[,2]=as.numeric(codeSignature[,2])
usethis::use_data(codeSignature,overwrite = T)
