## these two data sets are generated by
#testdataCont=power_compare(family="cont", Niter=1, sgdata=sgdata, bmrpars=log(BMR), betaf0=1,Nsample=50,beta_gc=c(1.2,Fe),par=c(0,5,0.1,1))
#testdataBinary=power_compare(family="binary", Niter=1, sgdata=sgdata, bmrpars=log(BMR), betaf0=1,Nsample=50,beta_gc=c(1.2,Fe),par=c(0.8,0.2))
# diffdriver version: diffdriver-702a73fa3decf14e942dcf702ea12cd38ba32b2a
testdataBinary=load("C:/Users/Jie Zhou/Desktop/Rtest/testdataBinary.rda")
testdataCont=load("C:/Users/Jie Zhou/Desktop/Rtest/testdataCont.rda")
usethis::use_data(testdataBinary, overwrite = T)
usethis::use_data(testdataCont, overwrite = T)


hotspotseq=function(hmm,sgdata){
  pos=sort(unique(do.call(rbind,sgdata)$start))
  seqt=sample(x=c(0,1),size=1,prob =c(hmm[1],hmm[2]))
  for (i in 2:length(pos)) {
    a=ifelse(seqt[i-1]==0,sample(x=c(0,1),size=1,prob =c(hmm[3],hmm[4])),
             sample(x=c(0,1),size=1,prob =c(hmm[5],hmm[6])))
    seqt=c(seqt,a)
  }
  hotseq=cbind(start=pos,seqt=seqt)
  return(hotseq)
}
hotseq=hotspotseq(hmm,sgdata)

usethis::use_data(hotseq, overwrite = T)
