library(devtools)
load_all("../../../..")
## parameters setting
set.seed(119)
binary=T
bmrpars=log(BMR)
betaf0=1
beta_gc=c(1,0)
para=c(0.8,0.2)
N=100

## Data generated by Jie's rsparsematrix-based simulation function
 
rr1=c()
rr1_approx=c()
for (i in 1:N) {
  simdata <- simulate_1funcv(binary,sgdata, bmrpars, betaf0, Nsample=1000, beta_gc, para,hotseq0,hmm)
  ssgdata=simdata$annodata
  mut <- do.call(rbind, simdata$mutlist)
  bmrmtx <- do.call(rbind, simdata$bmrmtxlist)
  hotsize <- do.call(c,simdata$hotsize)
  e <- simdata$pheno
  funcv <- unlist(lapply(ssgdata, "[[", "functypecode"))
  ef <- simdata$efsize
  fe=vector("list",4)
  fe[[1]] <- c(ef$beta_gc[1], ef$beta_gc[1] + ef$beta_gc[2])[as.factor(funcv)]
  fe[[2]] <- c(ef$avbetaf1, ef$avbetaf1 + ef$avbetaf2)[as.factor(funcv)]
  fe[[3]] <- rep(ef$betaf1f2, length(funcv))
  fe[[4]] <- rep(ef$avbetaf1f2, length(funcv))
  mr <- bmrmtx + ef$betaf0
  rr1=c(rr1,ddmodel(mut,e, mr, fe[[2]])$pvalue)
rr1_approx=c(rr1_approx,ddmodel_binary_simple(mut,e,mr,fe[[2]])$pvalue)
}
summary(rr1)
## Data generated by Siming's simulation function
save(rr1,file="rr1.Rd")
save(rr1_approx,file="rr1_approx.Rd")
